[tool.poetry]
name = "mediaforge"
version = "1.0.0"
description = "A Discord bot for editing and creating videos, images, GIFs, and more!"
authors = ["reticivis"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
#nextcord = { git = "https://github.com/nextcord/nextcord.git", allow-prereleases = true, extras = ["speed"] }
"discordlists.py" = { git = "https://github.com/HexCodeFFF/discordlists.py.git" }
aiofiles = "^0.8.0"
humanize = "^4.2.3"
coloredlogs = "^15.0.1"
selenium = "^4.3.0"
Pillow = "^9.0.0"
numpy = "*"
pyautotune = { git = "https://github.com/HexCodeFFF/PyAutoTune.git" }
regex = "^2022.6.2"
pronouncing = "^0.2.0"
aiosqlite = "^0.17.0"
psutil = "^5.9.1"
aubio = "^0.4.9"
apng = "^0.3.4"
docstring-parser = "^0.14.1"
yt-dlp = "^2022.6.29"
emojis = "^0.6.0"
python-magic = { version = "^0.4.13", markers = "sys_platform != 'win32'" }
python-magic-win64 = { version = "^0.4.13", markers = "sys_platform == 'win32'" }
requests = "^2.28.1"

pyttsx3 = "^2.90"
# comtypes on pypi is fucked on 3.8+
nextcord = { version = "^2.0.0", extras = ["speed"] }


[tool.poetry.dev-dependencies]
#aiohttp = { version = "^3.8.1", extras = ["speedups"] }
#setuptools = "^60.5.0"
isort = "^5.10.1"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
