[tool.poetry]
name = "mediaforge"
version = "1.0.0"
description = "A Discord bot for editing and creating videos, images, GIFs, and more!"
authors = ["reticivis"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = { git = "https://github.com/Rapptz/discord.py.git", allow-prereleases = true, extras = ["speed"] }
aiofiles = "^0.8.0"
humanize = "^4.3.0"
coloredlogs = "^15.0.1"
selenium = "^4.4.3"
Pillow = "^9.0.0"
numpy = "^1.23.2"
pyautotune = { git = "https://github.com/HexCodeFFF/PyAutoTune.git" }
regex = "^2022.8.17"
pronouncing = "^0.2.0"
aiosqlite = "^0.17.0"
psutil = "^5.9.1"
aubio = "^0.4.9"
apng = "^0.3.4"
docstring-parser = "^0.14.1"
yt-dlp = "^2022.9.1"
emojis = "^0.6.0"
python-magic = { version = "^0.4.13", markers = "sys_platform != 'win32'" }
python-magic-win64 = { version = "^0.4.13", markers = "sys_platform == 'win32'" }
requests = "^2.28.1"
pypiwin32 = "^223"
# poretry doesnt like discord.py idfk
aiohttp = "^3.8.1"
aiodns = "^3.0.0"
cchardet = "^2.1.7"
"discordlists.py" = "^1.1.1"

[tool.poetry.dev-dependencies]
#aiohttp = { version = "^3.8.1", extras = ["speedups"] }
#setuptools = "^60.5.0"
isort = "^5.10.1"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
