name: Feature Request
description: Suggest an idea
labels: [ suggestion ]
body:
  - type: markdown
    attributes:
      value: A feature request under issues must be a precise and implementable feature. For very vague/broad requests, post to the ideas page in discussion.
  - type: textarea
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to be added and why.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is and how this feature would solve it
      placeholder: I'm always frustrated when...
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Anything Else
      description: Put any screenshots or other context/details about the feature here.