name: Unban Request
description: Request to be unbanned from the public MediaForge bot
labels: [ "unban request" ]
title: Unban request for <YOUR NAME HERE>
body:
  - type: input
    attributes:
      label: Your Discord tag
      description: Your username AND descriminator
      placeholder: "@MediaForge#5871"
    validations:
      required: true
  - type: input
    attributes:
      label: Your Discord ID
      description: you can get this by enabling developer mode, right-clicking on yourself, and clicking "copy ID". this is NOT your 4 digit discriminator and will likely be 18-22 digits long.
      placeholder: "780570413767983122"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why were you banned?
      description: if the bot gives you a specific reason, copy-paste it here. If not, bans are typically issued due to the text of a command, what were the last few commands you sent before you were banned?
      placeholder: I was banned because...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why should you be unbanned?
      placeholder: I should be unbanned because...
    validations:
      required: true